### ISSUE TITLE
Restart dev server on edit

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#99]
Add `--respawn --transpile-only` options to server start script.

**Comment by one2code** [comment]
I made a mistake, so this one will be a few more extra steps. Turns out that only ts-node-dev has the built-in respawn and --transpile-only functionality, and not the original ts-node. So for this step, it will require an uninstall of ts-node, replacing it with ts-node-dev and the script you posted. This is a much better alternative than nodemon for TS (more reliable).
